BUILDER-96: Create env that has ACS, APS 2.1 and Event Gateway
Activiti/activiti-cloud-charts pull request #45
Opened 2019-02-05 14:05 UTC by cristina-sirbu

Replace Activiti-Keycloak with Alfresco-Identity-Service

2019-02-05 14:21 UTC, salaboy commented
@igdianov @almerico can you guys review as well?

2019-02-05 14:27 UTC, ryandawsonuk commented on infrastructure/requirements.yaml
> -  condition: infrastructure.activiti-keycloak.enabled,activiti-keycloak.enabled
I'd prefer if we still have conditions so that AIS can be removed if users want

2019-02-05 14:27 UTC, salaboy commented on infrastructure/requirements.yaml
> -  condition: infrastructure.activiti-keycloak.enabled,activiti-keycloak.enabled
👍

2019-02-05 14:34 UTC, ryandawsonuk commented
Would definitely like to go this way as per https://github.com/Activiti/Activiti/issues/2450 and these chart changes look good to me... but then we need to do the other things explained in that issue

2019-02-05 14:54 UTC, cristina-sirbu commented
I added to condition for the requirement. I missed that. Good spot! 👍

2019-02-13 22:57 UTC, igdianov commented on activiti-cloud-full-example/values.yaml
> +        hosts: *keycloakhost
Not sure if this is going to work with injecting raw url from line `#8` into Keycloak ingress hosts... We should try to apply common chart approach to template keycloak host into Ingress resource using common template, so that we can avoid using Helm references that limit using Helm install from shell or CI/CD environment.

2019-02-13 22:58 UTC, igdianov commented on activiti-cloud-full-example/values.yaml
> +            - "http://activiti-keycloak.REPLACEME/*"
These are also should be using common chart to be injected into Keycloak deployment via realm template.

2019-02-13 23:04 UTC, igdianov commented on activiti-cloud-full-example/values.yaml
> +    url: &keycloakhost "http://activiti-keycloak.REPLACEME/auth"
Use of value references limits the reuse of the chart with Helm shell, CI/CD, and value.yaml overrides. The references work only within the defined scope. If someone provides values.yaml or uses Helm install with --set option to customize keycloak url value, this chart configuration will break and install wrong values in origin and Ingress hosts.

2019-02-13 23:05 UTC, igdianov requested changes
We should use common chart approach with scoped templates to automatically generate and inject correct values provided via global values...

2019-02-18 12:02 UTC, ryandawsonuk commented
I'm thinking the easiest way to get this working with the new templating of URLs and common chart stuff is to wrap identity-service in an activiti-keycloak chart and let activiti-keycloak chart provide the ingress. Unfortunately to do that I would need to be able to disable the ingress of the identity-service and [it currently doesn't support that](https://github.com/Alfresco/alfresco-identity-service/blob/master/helm/alfresco-identity-service/templates/identity-ingress.yaml#L3).

2019-02-18 12:28 UTC, ryandawsonuk commented
I've tried vendoring the chart and adding the option to turn off the ingress but then I hit the problem that it requires a persistent volume for identity service postgres:

`persistentvolumeclaim "alfresco-volume-claim" not found`

2019-02-18 13:19 UTC, ryandawsonuk commented
I've [created a new branch that builds on top of this ](https://github.com/Activiti/activiti-cloud-charts/commits/ryan-identity-service)and tries to disable the ingress and persistence in the identity service chart so that we can use the common template approach to generate ingress url.

In that branch I'm able to deploy everything and see it come up and get into the keycloak admin console and see the users and roles there. Almost everything is working... only problem is that the applications do not appear to be taking the client name 'alfresco' and instead the client name they expect remains 'activiti' so the tokens get rejected.

2019-02-18 15:32 UTC, svidrascu commented
@ryandawsonuk 
Probably because of this -> https://github.com/Activiti/activiti-cloud-modeling/issues/78
hit my head to this today also.

go with ...
activiti-cloud-full-example:
  activiti-cloud-modeling:
    backend: 
      extraEnv: |
        - name: "ACT_KEYCLOAK_REALM"
          value: "alfresco"
        - name: "ACT_KEYCLOAK_RESOURCE"
          value: "alfresco"

2019-02-18 15:52 UTC, ryandawsonuk commented
I did hit that and [had to change it, at least for the charts in this repo](https://github.com/Activiti/activiti-cloud-charts/commit/9ba9fb2dee4e0cf7d08a7e79c634a13ba32e3996). The one you reference in the other repo is basically [a duplicate that we use for the internal pipelines](https://github.com/Activiti/Activiti/issues/2269).

Now I'm able to at least [get tokens in the tests by parameterising the client](https://github.com/Activiti/activiti-cloud-acceptance-tests/pull/126/files). Unfortunately I then get 403 Forbidden errors in the services.

2019-02-19 09:39 UTC, ryandawsonuk commented
I gave the client/client user the same roles as it has in the activiti realm json file and now the acc tests pass from a deployment in the[ ryan-identity-service branch](https://github.com/Activiti/activiti-cloud-charts/tree/ryan-identity-service)

2019-02-20 11:45 UTC, ryandawsonuk commented
Closing this so we can review https://github.com/Activiti/activiti-cloud-charts/pull/51 , which builds on top of the commits

2019-02-20 11:45 UTC, closed without merging